Development testing clients
threefoldtech/js-ng pull request #435
Opened 2020-08-16 08:31 UTC by Dina-Abd-Elrahman

Docker client

2020-08-16 11:04 UTC, AhmedHanafy725 commented on tests/clients/docker_client.py
> +        self.info("Check that docker is started correctly")
Repeated line

2020-08-16 11:05 UTC, AhmedHanafy725 commented on tests/clients/docker_client.py
> +        #. Use stop method to stop docker container.
Need to check if it is running before stopping it.

2020-08-16 11:06 UTC, AhmedHanafy725 commented on tests/clients/docker_client.py
> +            self.assertTrue("No such container" in error.exception.args[0])
use `assertIn` instead

2020-08-16 11:07 UTC, AhmedHanafy725 commented on tests/clients/docker_client.py
> +            self.assertTrue("No such container" in error.exception.args[0])
use `assertIn`

2020-08-16 11:07 UTC, AhmedHanafy725 commented on tests/clients/docker_client.py
> +        for i in range(len(docker_list)):
Why not we loop on docker_list itself without len() and range()?

2020-08-16 11:10 UTC, AhmedHanafy725 commented on tests/clients/docker_client.py
> +            elif docker_list[i].short_id == DOCKER_ID_2:
what if it is not in the list?

2020-08-16 11:26 UTC, AhmedHanafy725 commented on tests/clients/docker_client.py
> +            self.assertTrue("Stop the container before attempting removal or force remove" in error.exception.args[0])
use `assertIn`

2020-08-16 11:28 UTC, AhmedHanafy725 commented on tests/clients/docker_client.py
> +        #. Try to delete the running docker using force=False option it should raise an error.
Need to check every time that the container is created before deleting it.

2020-08-18 11:26 UTC, AhmedHanafy725 commented on tests/clients/test_docker_client.py
> +            self.assertTrue("No such container" in error.exception.args[0])
use `assertIn`

2020-08-18 11:28 UTC, AhmedHanafy725 commented on tests/clients/test_docker_client.py
> +            DOCKER_ID_1 and DOCKER_ID_2,
Adding two object with `and` result always in the second object, so this check only checking that DOCKER_ID_2 in the list.

2020-08-25 08:12 UTC, abom requested changes

2020-08-25 08:12 UTC, abom commented on tests/base_tests.py
> +        self.info("Test case : {}".format(self._testMethodName))
what's self.info? and what about j.logger? we can even create custom format for tests if needed.

2020-08-25 08:21 UTC, merged