add test for sshkey and sshclient
threefoldtech/js-ng pull request #487
Opened 2020-10-25 09:36 UTC by mhost39

### Description
Test coverage for sshkey and sshclient

### Related Issues
https://github.com/threefoldtech/js-ng/issues/486

2020-10-25 23:46 UTC, xmonader commented on tests/clients/sshclient/test_sshclient.py
> +        return j.data.idgenerator.nfromchoices(10, string.ascii_letters)
can do j.data.idgenerator.chars(10) instead

2020-10-26 10:05 UTC, mhost39 commented on tests/clients/sshclient/test_sshclient.py
> +        return j.data.idgenerator.nfromchoices(10, string.ascii_letters)
some names invalid like name start with number 
![image](https://user-images.githubusercontent.com/31102305/97159214-360e6600-1783-11eb-95a8-d1f4bd7fb887.png)

2020-10-28 17:14 UTC, AhmedHanafy725 requested changes

2020-11-09 16:26 UTC, AhmedHanafy725 requested changes
Please generate the docs of these tests by running `make testdocs` in the repo home.

2020-11-09 16:26 UTC, AhmedHanafy725 commented on tests/clients/sshclient/test_sshclient.py
> +        self.container_id = self.docker_client.list()[0].id
In case there are more than container is running, this would get the wrong container.

2020-11-09 16:26 UTC, AhmedHanafy725 commented on tests/clients/sshkey/test_sshkey.py
> +        self.assertEqual(j.sals.fs.is_file(public_key_path), True)
can we use `assertTrue`?

2020-11-11 08:00 UTC, AhmedHanafy725 approved these changes

2020-11-15 08:01 UTC, merged